"""First migration3

Revision ID: ac8cfbda3e59
Revises: 
Create Date: 2024-11-13 03:30:37.162249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8cfbda3e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadastr_number', sa.String(length=17), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.CheckConstraint('latitude <= 180.0 AND latitude >= -180.0', name='can be between -180 and 180'),
    sa.CheckConstraint('longitude <= 90.0 AND longitude >= -90.0', name='can be between -90 and 90'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('cadaster')
    # ### end Alembic commands ###
